name: Update OAM Component Image

on:
  workflow_call:
    inputs:
      component:
        description: Name of the component to update
        required: true
        type: string
      image:
        description: New image to set
        required: false
        type: string
      oam-file:
        description: OAM file to update
        required: true
        type: string

permissions:
  contents: write # required for pushing commits

jobs:
  update-oam-component-image:
    name: Update OAM Component Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Update OAM Component Image
        run: |
          git pull
          yq -i '.spec.components |= with(.[]; select(.name == "${{ inputs.component }}") .properties.image = "${{ inputs.image }}")' ${{ inputs.oam-file }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "update image for component ${{ inputs.component }}"
          git push
